# Generated by Django 6.0.1 on 2026-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_make_join_code_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
